server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE

  cloud:
    config:
      uri:
        - http://localhost:9196

logging:
  file:
    name: C:/Users/Azer/Desktop/logs/microservice.log

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZona: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost